### PR TITLE
Fix el9stream automation

### PR DESCRIPTION
**Pull request by mnecas**
- Add el9stream packages

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Comment by mwperina** [comment]
Maybe renaming existing `build-artifacts.packages` to `build-artifacts.packages.el8` would solve the issue with el9 ...

**Comment by marchukov** [comment]
@mnecas you are missing check-patch.packages.el9stream. The thing is that - check-patch control what happen before the patch is merged and right now it is symlinked to build-artifacts.packages and thus during patch check it executes your el8 code. Thus you need to create check-patch.packages.el9stream that is symlinked to build-artifacts.packages.el9stream

Not that there is python3-entrypoints in el9stream, so it will still fail. But I guess we need to make sure it executes the correct configuration first.

**Review by marchukov — APPROVED** [review]

**Review by mwperina — APPROVED** [review]
+1

**Pull request merged**
