### PR TITLE
Add fcf-protection to xml.cpython compilation

### PR DESCRIPTION
**Pull request by oliel**
Signed-off-by: Ori Liel <oliel@redhat.com>

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
Looks good to me.

Marcin, isn't it something which we should use also in other python projects?

**Comment by nirs** [comment]
This looks like an issue in gcc/annobin/rpmdiff, and not in this project.

See also https://github.com/oVirt/ovirt-imageio/issues/49

**Comment by nirs** [comment]
See also https://bugzilla.redhat.com/2065867

**Comment by oliel** [comment]
As per Nir's comment, this is a more general problem and needs to be addressed elsewhere, not manually in the python-sdk

**Pull request closed without merging**
